#!/bin/bash
#!-*- sh -*-
#
# Abs: multiplierClientRunner executes the MultiplierClient EV4 java client.
#
# Rem: multiplierClient is a simple example of an E4C client demonstrating how to
#      use EPICS v4 "Normative types" by illustrating the client and server sides
#      in which an EPICS V4 server returns one of the Normative Types, an NTScalar,
#      back to the client. 
#
# Usage: Execute multiplierClientRunner at any time while multiplierServerRunner is running. 
#        You should see something like the following.
# 
#   > ./multiplierClientRunner 
# 
#   request = 
#   structure 
#      double a 12.3
#      double b 45.6
#  
#   value = 560.88
#   descriptor = The product of arguments a and b
#
#   Whole result structure toString =
#   uri:ev4:nt/2012/pwd:NTScalar 
#      double value 560.88
#      string descriptor The product of arguments a and b
#
# 
# Ref: 
# ----------------------------------------------------------------------------
# Auth: 14-Sep-2012, Greg White (greg@slac.stanford.edu)
# Mod:  
# ============================================================================
source multiplier_setup.bash

java -client illustrations.multiplierService.MultiplierClient
