#!/bin/bash
#!-*- sh -*-
#
# Abs: helloServerRunner executes the helloServer EV4 server.
#
# Rem: helloServer is a simple example server demonstrating support for
#      a client/server environment in EPICS V4. 
#
# Usage: Execute helloServerRunner prior to executing helloClientRunner.   
# 
#         > ./helloServerRunner    
# 
# Ref: 
# ----------------------------------------------------------------------------
# Auth: 14-Sep-2011, Greg White (greg@slac.stanford.edu)
# Mod:  
# ============================================================================
source helloWorld_setup.bash

java -server services.helloWorld.HelloService