#! /bin/bash
#!-*- sh -*-
#
# Abs: rdbServerRunner executes the rdbService in an EV4 
#      server.
#
# Rem: rdbService is a simple service for getting data out of a relational database
#      such as Oracle. 
#
#      THE ORDER OF ARGS IS IMPORTANT. -records must follow -structures.
#
# Usage: Execute rdbServerRunner prior to executing rdbClientRunner.   
# 
#         > ./rdbServerRunner    
# 
# Ref: 
# ----------------------------------------------------------------------------
# Auth: 13-Oct-2011, Greg White (greg@slac.stanford.edu)
# Mod:  
# ============================================================================

source rdb_setup.bash

java -server rdbService/RdbService
