#! /bin/bash
#!-*- sh -*-
#
# Abs: rdbServerRunner executes the example EPICS V4 RDB service.
#
# Rem: rdbService is a simple service for getting data out of a relational database
#      such as Oracle. 
#
# Usage: Execute rdbServerRunner prior to executing rdbClientRunner.   
# 
#         > ./rdbServerRunner    
# 
# Ref: 
# ----------------------------------------------------------------------------
# Auth: 13-Oct-2011, Greg White (greg@slac.stanford.edu)
# Mod:  
# ============================================================================

source rdb_setup.bash

java -server services/rdbService/RdbService
